print ("~~~~~~~~~~~~~~~ /('v')\ ~~~~~~~~~~~~~~~")
print ("PROGAM PENGHITUNGAN VOLUME BANGUN RUANG")
print ("~~~~~~~~~~~~~~~ \('v')/ ~~~~~~~~~~~~~~~")
print ("")
print ("Pilihlah salah satu bangun ruang yang ingin dihitung volumenya: ")
print ("1. Limas")
print ("2. Bola")
print ("3. Prisma")
print ("4. Kerucut")
print ("")
pilihan = int(input("Masukan pilihan anda: "))
if pilihan == 1:
    alas = int(input("Masukan panjang sisi alas limas: "))
    tinggi = int(input("Masukan tinggi limas: "))
    print ("Volume limas tersebut adalah ",(1/3)*(alas*alas)*tinggi)